### ISSUE TITLE
Usage for proportion estimates of spatial transcriptomics

### ISSUE THREAD

**Issue by franciscogrisanti** [shazanfar/scHOT#3]
Hi @shazanfar!

Thanks for this great package. I'm using scHOT in spatial transcriptomics for gene-gene interactions, but I also trying to run it with deconvolution proportion estimates with no luck. I was wondering if you have an implementation for this?

<img width="913" alt="image" src="https://user-images.githubusercontent.com/35009018/112205559-ea050780-8be2-11eb-99aa-1658143d3de5.png">

**Comment by shazanfar** [comment]
Hi Francisco,

Thanks for your question. It's odd that the span of the weightMatrix is defaulting to 0. The missing value error I believe comes about when there exists a row of zeroes within the weight matrix, and this would happen if the span is zero.

I would suggest allowing the span parameter to be set to a specified value, like the default 0.05, and see if you still run into any issues with that? Otherwise, you may be able to specifically enter the desired weighting scheme by including the "weightMatrix" parameter in the scHOT function call. The weight matrix has the same number of columns as the number of observations/cells in the data, and the rows corresponds to each of the individual weightings to use, and can be generated using scHOT::spatialWeightMatrix().

I hope that's useful? Please let me know how you go and if there's any further issues, feel free to send through a minimal sample of the type of data structure you're working with.

Cheers,
Shila
